import type { Metadata } from 'next'
import './globals.css'
import { Trispace } from 'next/font/google'
import Providers from './_providers'
import { AppSidebar } from './_layout/sidebar/sidebar'
import { SidebarInset, SidebarTrigger } from '@/shared/ui/sidebar'
import { Separator } from '@radix-ui/react-separator'
import Header from './_layout/header/header'

const trispace = Trispace({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={trispace.className}>
                <Providers>
                    <AppSidebar />
                    <SidebarInset className='w-full'>
                        <Header />
                        <div className="flex flex-1 flex-col gap-4 p-2 md:p-4 pt-0">
                            {children}
                        </div>
                    </SidebarInset>
                </Providers>
            </body>
        </html>
    )
}
