import type { Metadata } from 'next'
import './globals.css'
import { Trispace } from 'next/font/google'
import Providers from './_providers'
import { AppSidebar } from './_layout/sidebar/sidebar'
import { SidebarInset, SidebarTrigger } from '@/shared/ui/sidebar'
import { Separator } from '@radix-ui/react-separator'

const trispace = Trispace({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={trispace.className}>
                <Providers>
                    <AppSidebar />
                    <SidebarInset>
                        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                            <div className="flex items-center gap-2 px-4">
                                <SidebarTrigger className="-ml-1" />
                                <Separator orientation="vertical" className="mr-2 h-4" />
                            </div>
                        </header>
                        <div className="flex flex-1 flex-col gap-4 p-4 pt-0">
                            {children}
                        </div>
                    </SidebarInset>
                </Providers>
            </body>
        </html>
    )
}
