import type { Metadata } from 'next'
import '../globals.css'
import { Trispace, Nunito } from 'next/font/google'
import { SidebarInset, SidebarTrigger } from '@/shared/ui/sidebar'
import Header from '../_layout/header/header'
import { AppSidebar } from '../_layout/sidebar/sidebar'
import Providers from '../_providers'
import { notFound } from 'next/navigation'
import { getMessages } from 'next-intl/server'
import { routing } from '@/shared/lib/i18n/routing'
import {setRequestLocale} from 'next-intl/server';

const trispace = Trispace({ subsets: ['latin'] })
const nunito = Nunito({
    weight: '600',
    subsets: ['cyrillic'], 
  });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
    params: { locale }
}: Readonly<{
    children: React.ReactNode
    params: { locale: string }
}>) {

    if (!routing.locales.includes(locale as any)) {
        notFound();
    }

    await setRequestLocale(locale);

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={nunito.className}>
                <Providers>
                    <AppSidebar />
                    <SidebarInset className='w-full'>
                        <Header />
                        <div className="flex flex-1 flex-col gap-4 p-2 md:p-4 pt-0 ">
                            {children}
                        </div>
                    </SidebarInset>
                </Providers>
            </body>
        </html>
    )
}
