import type { Metadata } from 'next'
import '../globals.css'
import { notFound } from 'next/navigation'
import { Locale, routing } from '@/shared/lib/i18n/routing'
import { setRequestLocale } from 'next-intl/server';
import { SidebarInset } from '@/shared/ui/sidebar';
import { Toaster } from '@/shared/ui/toaster';
import Header from '../_layout/header/header';
import Providers from '../_providers';
import { Nunito } from 'next/font/google';
import AppSidebar from '../_layout/sidebar/sidebar';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const nunito = Nunito({
    weight: '600',
    subsets: ['cyrillic'],
});


export default async function RootLayout({
    children,
    params
}: Readonly<{
    children: React.ReactNode
    params: Promise<{ locale: Locale }>
}>) {
    const { locale } = await params

    if (!routing.locales.includes(locale as any)) {
        console.log('locale should be catched')
        return notFound()
    }

    await setRequestLocale(locale);

    return (
        <html lang={locale} suppressHydrationWarning>
            <body className={nunito.className}>
                <Providers>
                    <AppSidebar />
                    <SidebarInset className='w-full'>
                        <Header />
                        <div className="flex flex-1 flex-col gap-4 p-2 md:p-4 pt-0 ">
                            {children}
                        </div>
                    </SidebarInset>
                </Providers>
                <Toaster />
            </body>
        </html>
    )
}
